name: QA on PR

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Is linted
        run: pnpm lint
      - name: Is built
        run: |
          if [ -n "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'index.ts')" ]; then
            echo "index.ts was changed"
            if [ -n "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'index.js')" ]; then
              echo "index.js was updated"
            else
              echo "index.js was not updated"
              exit 1
            fi
          fi
      - name: Run tests
        run: pnpm test
